### PR TITLE
Checkbox and radio CSS

### PR DESCRIPTION
**Pull request by jmealing**
New css for checkboxes and radio buttons "gc-form"

### CODE REVIEW

**Comment by duboisp** [comment]
To fix the Travis-CI build script you will need to:
* Order the CSS property name alphabetically for within each block of styling
* Use the tabs spacing character instead on using the space character.

**Comment by jmealing** [comment]
Thanks Pierre, I'll resubmit with those fixes once I'm back from training this week.

**Comment by delisma** [comment]
This should be closed since PR #1682 is taking care of it

**Comment by duboisp** [comment]
Replaced by #1709

**Pull request closed without merging**
