### PR TITLE
Service initiation pages: Changed right panel's sections to asides.

### PR DESCRIPTION
**Pull request by EricDunsworth**

### CODE REVIEW

**Comment by shawnthompson** [comment]
This comment was meant for here:
>@EricDunsworth we've been talking about this lately and we are trying to decide to use the `aside` or not...

**Comment by EricDunsworth** [comment]
Umm here's a quote of my related response lol.

> @shawnthompson IMO it'd be wise since asides are more appropriate than sections for that kind of content.

**Comment by shawnthompson** [comment]
@MaximMartel @lucas-hay I'd like to merge this PR, once @EricDunsworth fixes the conflic, but I think you should make sure the templates in AEM get updated with this change also.

**Comment by EricDunsworth** [comment]
@shawnthompson Just updated this PR and fixed its conflicts :).

**Pull request merged**
