### PR TITLE
Site: Changed mega menu HBS files to use i18n variables.

### PR DESCRIPTION
**Pull request by EricDunsworth**
This should be merged in after #1178. Once that happens, this PR might run into merge conflicts. Should be super easy to resolve them if it comes to that.

### CODE REVIEW

**Comment by nschonni** [comment]
You'd probably get more value out of this if everything was in the i18n, because then you'd be getting ride of one of the templates and just compiling it to 2 (or more) languages

**Comment by EricDunsworth** [comment]
@nschonni I agree. My main goal with this PR was solely to eliminate the need to re-declare the same top-level mega menu links twice in [the "mini" mega menu](https://github.com/wet-boew/GCWeb/blob/master/site/includes/sitemenucontent.hbs) (via [/site/data/i18n/en.json](https://github.com/wet-boew/GCWeb/blob/master/site/data/i18n/en.json)) and [the "full" mega menu](https://github.com/wet-boew/GCWeb/blob/master/site/includes/fullmenu-en.hbs). That way, if those particular links change again the future, they'll only need to be updated in one spot for per language.

Doing it for the rest of the "full" mega menu's content might take a while (likely means introducing > 156 new variables per language), but I think I'll give it a shot since I see the value in what you're suggesting.

**Comment by MichaelDalrymple** [comment]
Question: Does anyone know the process for informing departments when the mega menu is updated? I'm told that each department needs to hardcode links into their template for non-javascript browswing. Wondering how each dept is informed of their need to update this content. Thanks.

**Comment by shawnthompson** [comment]
@MichaelDalrymple There is a CDN for the mega menu, just like the GoC Activities and Initiatives.
[Travel.gc.ca](https://travel.gc.ca/) is using it. It uses cross domain AJAX to pull it in.

**Comment by rlambert27** [comment]
@shawnthompson I think @MichaelDalrymple means how do we know when to update the hard-coded links that appear when Javascript is disabled if we can't grab them from the CDN.

I know that for the CDTS solution we release new static files every release to account for any GCWeb changes including the mega menu links (http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_(CDTS)).

**Comment by shawnthompson** [comment]
@MichaelDalrymple presently there's no notification for departments. Even GCWeb needed to be updated and was notified of any changes.

cc/ @lucas-hay @MaximMartel @masterbee

**Comment by MichaelDalrymple** [comment]
Thanks Shawn. So, this is a problem for us internally and has been raised to my attention a few times now. Any idea on how to get the notification process changed or who is responsible for notifying depts?

**Comment by lucas-hay** [comment]
@MichaelDalrymple, the service desk from Principal Publisher (Service Canada) send out an email anytime there are mega menu updates. We have a list of contacts for each site/department (that we are aware of) that are using the GCWeb templates. We update the CDN, and send an email, as there are a few sites that are not using the CDN. Can you please look me up in GEDS and I will get your contact added to the list.

**Pull request merged**
