### PR TITLE
Site menu: Fix broken layout for site menu - IE7

### PR DESCRIPTION
**Pull request by m14e**
(1) Fix broken layout for site menu - IE7; (2) workaround for IE z-index issues; (3) fix horizontal placement

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
I will fix this pr on monday

**Comment by masterbee** [comment]
@LaurentGoderre - ok but I just want to be sure that we are working in the right direction since IE7 seems a bit to old on the browser support list, and do not want to add more support than necessary, or even work that will be removed shortly after.

What is your take on this?

**Comment by LaurentGoderre** [comment]
We don't have to make it look good, just functional and this is a small footprint. We should segregate it even further.

**Comment by pjackson28** [comment]
The fixes could be added if they don't affect the download size of other browsers (excluding IE8) but as a project IE7 is outside of the support window for WET so we will not be testing for it. The earliest version of IE that we currently support is IE8 and even that support is coming into question as visits with IE8 are dropping below the 5% support threshold. As reminder, here is the browser support criteria for WET:

* The current and previous major version of each browser that accounts for at least 5 per cent of visits(1) to the website;
* Any major version of a browser that, on its own, accounts for at least 5 per cent of visits(1) to the website; and
* The current major version of each mobile browser that accounts for at least 5 per cent of mobile device visits(1).

(1) For Government of Canada websites: Visits to all public-facing Government of Canada websites and web applications, excluding visits from Government of Canada workstations.

**Comment by LaurentGoderre** [comment]
Is it possible that many of those IE7 come from service points instead of users devices ?

**Comment by pjackson28** [comment]
Another possibility is that certain web servers and/or browsers could be configured in such a way as to trigger compatibility mode in IE (which is effectively IE7). We've seen that a few times with GC websites and GC workstations where it caused IE9 and even IE10 to go into compatibility mode despite accessing a public-facing website (normally this behaviour is reserved or intranets). This was easily fixed on the server by doing the fixes described on the following page: http://wet-boew.github.io/v4.0-ci/docs/server-en.html

**Comment by MRicher** [comment]
We added the condition to force out from compatibility mode for canada.ca with the mod_headers.c in Apache for this issue.

**Comment by LaurentGoderre** [comment]
Hmmm...there is one problem. It seems like there is no IE8 stylesheret for this theme. Adding one would require a markup change...

What do you think @masterbee

**Comment by masterbee** [comment]
@LaurentGoderre - yep I figured and I am hesitant since we will need to create more files and for a browser that is not supported. If this was a simple inclusion to existing files I would gladly say sure, but adding more files for a browser that is not supported makes me think we are heading the wrong direction. As @pjackson28 said earlier lets keep to our defined criteria since messing with grunt task and adding new files have proven to be problematic in the past and since we will not be testing for it, makes me more uneasy about adding an addition resource to the theme for it.

Make sense?

**Pull request closed without merging**
