### PR TITLE
Updated Theme page - removed alert banner and change h1 title

### PR DESCRIPTION
**Pull request by MaximMartel**
As per Content and IA Spec 3.2

### CODE REVIEW

**Comment by MaximMartel** [comment]
@shawnthompson  @lucas-hay

**Comment by MaximMartel** [comment]
https://maximmartel.github.io/GCWeb-UpdateTheme/theme-en.html

**Comment by MaximMartel** [comment]
@DK-TBS

**Comment by DK-TBS** [comment]
English theme page looks good!

**Comment by MaximMartel** [comment]
You can hit the language toggle on the example page for the french :)
If you don't mind checking it real quick @DK-TBS

**Comment by DK-TBS** [comment]
Ah, okay cool - checked the French version, it looks good too  :)

**Pull request merged**
