### PR TITLE
Institutional template - Use proper grid when displaying Follow us content block

### PR DESCRIPTION
**Pull request by duboisp**
@lucas-hay see the code change

Also, the handlebar conditional need to be a negative instruction, then you will be able to remove the "else".

### CODE REVIEW

**Comment by duboisp** [comment]
see http://universallabs.org/wet/labs/pr1320/unmin/institution-arms-en.html

**Comment by lucas-hay** [comment]
@duboisp 
Any idea how to deal with the float right (inside follow.hbs) in small view when we remove the following block of code from _base.css?

```xml

 +/* temporarily adding deleted WET styles back to help with right colum issues in GCWEB */
 +
 +/**
 +  *	Disable pull-right/left on grid columns that do not match the current
 +  *	breakpoint
 +  */
 +@media (max-width: $screen-xs-max) {
 +	.pull-left,
 +	.pull-right {
 +		&[class*=col-sm],
 +		&[class*=col-md],
 +		&[class*=col-lg],
 +		&[class*=followus] {
 +			float: none !important;
 +		}
 +	}
 +}
 +
 +@media (min-width: $screen-sm-min) and (max-width: $screen-sm-max) {
 +	.pull-left,
 +	.pull-right {
 +		&[class*=col-md],
 +		&[class*=col-lg],
 +		&[class*=followus] {
 +			float: none !important;
 +		}
 +	}
 +}
 +
 +@media (min-width: $screen-md-min) and (max-width: $screen-md-max) {
 +	.pull-left,
 +	.pull-right {
 +		&[class*=col-lg],
 +		&[class*=followus] {
 +			float: none !important;
 +		}
 +	}
 +} 
```

**Comment by duboisp** [comment]
we can add ```col-xs-12```, that will remove the pull-right effect

**Comment by lucas-hay** [comment]
I tested and it does not work on the inner pull right.

**Comment by duboisp** [comment]
@lucas-hay there is an issue with the ```col-md-auto``` it look like it do get overwritten with the media query when using ```col-xs-12```.

I will take a look later this evening.

**Comment by duboisp** [comment]
@lucas-hay see http://universallabs.org/wet/labs/pr1320/unmin/institution-arms-en.html 

FYI - that working example to do not include the work around that you mentioned previously on comments. I assume the removal of that work around will be made in a future version of gcweb.

**Pull request merged**
