### PR TITLE
Topic template: content edits

### PR DESCRIPTION
**Pull request by Garneauma**

### CODE REVIEW

**Review by duboisp — APPROVED** [review]
Reviewed and this is only a content change.

**Review by duboisp — CHANGES_REQUESTED** [review]
Waiting for the request approval

**Comment by Garneauma** [comment]
@duboisp Approval received on August 29th (just realized that Kevin meant he was approving the changes and not that he is in the process of aproving).

**Review by duboisp — APPROVED** [review]
Was approved by PP on August 29 at 11h47

**Pull request merged**
