### PR TITLE
URL mapping: Add action to pre-set value on input

### PR DESCRIPTION
**Pull request by GormFrank**
Execute pre-configured action based on url query string to set value on an input.

### CODE REVIEW

**Review by duboisp — COMMENTED** [review]
Check what we did for the data-json regarding to update form input

**Comment by duboisp** [comment]
I added the support for setting value on attribute and properties. 

* [ ] Documentation and the working example need to be completed.

**Comment by Ricokola** [comment]
Here are the steps to pre-filter results using a value via URL mapping on page load:

1. Set a JSON Manager component has dataset which include a unique ID and a "name" parameter. (Ex: `<div id="jmexample1" data-wb-jsonmanager='{"name": "example1"}'></div>`)
2. Set the URL Mapping component to add value to the dataset
```
"action": "patch",
"source": "#jmexample1",
"match": "ab|bc|mb|nb|nl|nt|ns|nu|on|pe|qc|sk|yt|all",
"base": "/province",
"default": "all",
"patches":
{
	"op": "add",
	"path": "{base}",
	"value": "{qval}"
}
```
3.

**Comment by GormFrank** [comment]
@Ricokola Thank you for this alternative, it would be nice to eventually create  a "Tips & tricks - how to preset value on load" page in the other components section in GCWeb to share with everyone more formally how to accomplish such thing :)

I will now close my PR.

**Pull request closed without merging**
