### PR TITLE
Added RAP CSS fix - Hide textarea and hide Other checkbox

### PR DESCRIPTION
**Pull request by MaximMartel**
Moved the RAP stuff from defaults.scss to /template/_base.scss as well 
My fix is live 208 to line 222

### CODE REVIEW

**Comment by MaximMartel** [comment]
@lucas-hay @masterbee

**Comment by MaximMartel** [comment]
please see gh-pages : https://maximmartel.github.io/GCWeb-RAPFix/home-en.html to see the fix

**Comment by shawnthompson** [comment]
Why are you hiding this CSS and not just removing the HTML from the source code?

**Comment by MaximMartel** [comment]
We will remove the HTML later on.

**Comment by shawnthompson** [comment]
Why not remove it now?

**Pull request merged**
