### PR TITLE
Plugin stabilization - as discussed at the last WET roadmap meeting

### PR DESCRIPTION
**Pull request by duboisp**
This PR depends on the feature being stabilized in https://github.com/wet-boew/wet-boew/pull/9002

### CODE REVIEW

**Comment by GormFrank** [comment]
Approved during technical review upon successful testing. Also, we will wait until wet-boew/wet-boew#9002 is merged.

**Comment by duboisp** [comment]
I rebased, fixed the conflict and updated the package.json to use the latest wet-boew version considering some stabilized feature was move to wet-boew project.

**Comment by duboisp** [comment]
Fixed a conflict where it was erroneously importing from wet-boew theme. A corresponding fix was made into wet-boew where wet-boew provisional CSS feature was moved into the wet-boew core instead of the wet-boew theme

**Comment by duboisp** [comment]
This change is required because of departmental priority to deploying this minor release on Canada.ca by the end of this week.

**Pull request merged**
