### PR TITLE
CSS: Added a rule above the activities and initiatives block.

### LINKED ISSUE #997: GC-wide feature tiles - add line above heading in template
As discussed yesterday with @thomasgohard @lucas-hay @LaurentGoderre @nrustand92 @neoinsight @dk-tbs - in recent usability testing by Lisa from Neoinsight, when participants were using page templates ending with prev/next buttons (see also #970) at the bottom of the content area, they sometimes missed the buttons. 

The hypothesis is that the GC-wide feature image tiles were distracting users from noticing the buttons. To solve, agreed that Thomas and team would add a line above the "Government of Canada activities and initiatives" heading in the GCweb template.

Proposed timeline: next week for v.4.0.16? if not, then v4.0.17 ok.

### PR DESCRIPTION
**Pull request by thomasgohard**
Fixes #997.

### CODE REVIEW

**Comment by masterbee** [comment]
@thomasgohard - there is a sass error in the form validation mind taking a peak.

**Comment by nschonni** [comment]
The build error is from an upstream change to the latest SCSS-Lint that uses comments to exclude the linting. I'd suggest bumping the version used here to the same, or maybe just copying the Gemfile/Bundler config from upstream during the build.

**Comment by thomasgohard** [comment]
@nschonni #1004 seems to have made things worse. Still have the same error as the previous run, and four new ones:
```
./lib/wet-boew/src/base/forms/_base.scss:31 [W] Rule declaration should be followed by an empty line
./src/_defaults.scss:32 [W] Rule declaration should be followed by an empty line
./src/mobile-centre.scss:56 [W] Rule declaration should be followed by an empty line
./src/mobile-centre.scss:75 [W] Rule declaration should be followed by an empty line
./src/social-media-centre.scss:121 [W] Rule declaration should be followed by an empty line
```

None of these errors make sense. For example `./src/mobile-centre.scss:56` is a blank line.

**Comment by nschonni** [comment]
@thomasgohard you'll need to rebase to get the build fixes for your PR.
If you landed it now, it would pass when running the master merge build though.

**Comment by thomasgohard** [comment]
@nschonni yep. Rebase would have helped. I guess I was tired last week.

This is good to merge now @masterbee.

**Pull request merged**
