### PR TITLE
WET-413 Ajax Fetch WCAG Pre-assessment

### PR DESCRIPTION
**Pull request by jonasg-gc**

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
* [x] Update the index.json-ld with a link to the report.
* [x] need to test the web page to ensure they are function
  - Language link
  - Report should populate the page.

@AtlakM for you action.

**Comment by AtlakM** [comment]
> * [ ]  Update the index.json-ld with a link to the report.
> * [ ]  need to test the web page to ensure they are function
>   
>   * Language link
>   * Report should populate the page.
> 
> @AtlakM for you action.

page populates correctly

**Comment by AtlakM** [comment]
> > * [ ]   Update the index.json-ld with a link to the report.
> > * [ ]   need to test the web page to ensure they are function
> >   
> >   * Language link
> >   * Report should populate the page.
> > 
> > @AtlakM for you action.
> 
> page populates correctly

https://github.com/AtlakM/GCWeb/blob/wet-413-pre-assess-ajax-fetch/common/ajax-fetch/index.json-ld

**Review by duboisp — APPROVED** [review]
Tested by @AtlakM

**Pull request merged**
