### PR TITLE
Decreasing space between list group items at small screen size

### PR DESCRIPTION
**Pull request by zachfalsetto**

### CODE REVIEW

**Comment by thomasgohard** [comment]
Related to #971.

**Comment by thomasgohard** [comment]
@zachfalsetto can you post before/after screenshots.

**Comment by shawnthompson** [comment]
@zachfalsetto Can you post those screenshots? We'd like to see the difference before we merge.

**Comment by neoinsight** [comment]
Supporting @shawnthompson in request for screenshots. Would like to see and test again in the future.

**Comment by shawnthompson** [comment]
I'm finally reviewing this... sorry it took so long.
Would we want to do this globally in the theme or would we want to do it just to the step by step process pages?

**Comment by neoinsight** [comment]
@shawnthompson Good question! This is only for small screen size right - did you ever get the screenshots requested above? Would like to see. Need @dk-tbs input in terms of the global theme.

**Comment by shawnthompson** [comment]
I'm working with @dk-tbs on these changes now. I think I'll just put the it on the specific page and close this PR. We can look at doing it on the whole theme if we need other instances of the same thing on different templates.

**Comment by neoinsight** [comment]
@shawnthompson Ok, @dk-tbs and you have it in hand. Thanks for the Christmas present!

**Comment by DK-TBS** [comment]
I think the discussion is only related to that one kind of list-item, those big "step" links at the top of the service initiation template.  We don't want to affect ordinary list item elements elsewhere in the site, or anything.  @thomasgohard put together a good mockup of what they should look like in [this comment here](https://github.com/wet-boew/GCWeb/issues/971#issuecomment-101807940).

The most urgent goal is to make these things take up a lot less vertical space on mobile, which Thomas' sketch will help address.  But while we're at it, we should tighten them up on the larger screen sizes too, they don't need to be quite so big.  You want to tinker with it, or would you like me to try to settle on good paddings/margins in photoshop and send you a sketch?  I'm easy  :)

**Comment by shawnthompson** [comment]
Let's just do it on the actual template page. Just using negative margin like what @zachfalsetto did in this PR.

**Comment by shawnthompson** [comment]
How's this?

http://servicecanada.github.io/GCWeb/servicecomplexe/index-en.html

@DK-TBS, if you agree I'll put in a PR and we can close this issue for now.

**Comment by DK-TBS** [comment]
Nice;  big improvement.  Can we tighten up the padding inside those LI elements, as well?  If I give them padding: 4px 10px 4px 10px, they take up even less space, and come out looking more like Thomas' mockup...

screenshot

**Comment by neoinsight** [comment]
Nice!

**Comment by shawnthompson** [comment]
Done

http://servicecanada.github.io/GCWeb/unmin/servicecomplexe/index-en.html

**Pull request merged**
