### PR TITLE
Page details: remove share this page

### PR DESCRIPTION
**Pull request by Garneauma**
Changes related to WET-458

### CODE REVIEW

**Comment by Garneauma** [comment]
Pre-approved upon successful review.

**Review by Ricokola — APPROVED** [review]
Reviewed and tested locally and seems to works and implemented as expected.

**Review by duboisp — CHANGES_REQUESTED** [review]
À première vue, je crois qu'il nous manques un "deprecated" example qui contient le share this page. Je vois le code mais pas l'exemple associé.

**Review by duboisp — CHANGES_REQUESTED** [review]
In addition to the demoted working example, can you add a quick implementation for "Migration to v4" in the documentation? and mention this is the removal of "share this page" in the intro.

I completed the review and local testing. Other than that it should be good.

**Review by duboisp — DISMISSED** [review]
Reviewed and tested locally

All is documented, demoed and work as expected.

**Comment by duboisp** [comment]
This is a minor change because we demoted the pattern. We will deprecate officially that pattern at our next major release.

**Review by duboisp — APPROVED** [review]
Thanks for changing the version number for a minor change.

**Pull request merged**
