### PR TITLE
Footer: links updates, contextual, about site

### PR DESCRIPTION
**Pull request by Garneauma**
Reordering of the links in the "About government" section of the footer plus some minor text changes.

Changes related to WET-290

### CODE REVIEW

**Comment by duboisp** [comment]
Here a prototype build from this PR: https://universallabs.org/wet/labs/pr2043/index-en.html

Note: This change request is blocked until the User Acceptance Testing (UAT) has passed.

**Review by duboisp — CHANGES_REQUESTED** [review]
New change request:

* [ ] Update the h4 heading text under the "Government of Canada" (Jekyll variable `i18nText-themeLinks`) for:  "Themes and wide audiences" / "Thématiques et vaste auditoires"

**Comment by Garneauma** [comment]
> New change request:
> 
> * [x]  Update the h4 heading text under the "Government of Canada" (Jekyll variable `i18nText-themeLinks`) for:  "Themes and wide audiences" / "Thématiques et vaste auditoires"

Done.

**Comment by duboisp** [comment]
I updated our working example for UAT testing

Based on the commit: 7b74ce7
Working example: https://universallabs.org/wet/labs/pr2043/sites/footers/footers-en.html

**Comment by Garneauma** [comment]
PR rebased and conflicts resolved. Ready for another review.

**Comment by duboisp** [comment]
I recreated the demo with the latest change made yesterday.

Here the link for UAT:

* Complete site footer example and documentation:
  * [Footer](https://universallabs.org/wet/labs/pr2043/sites/footers/footers-en.html)
  * [Pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/footers-fr.html)
* Pages with all the different variation rendering of the site footer
  * [Hide 'Support' section from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-support-en.html)
  * [Masquer la section 'Soutien' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-support-fr.html)
  * [Hide 'About government' section from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-about-gov-en.html)
  * [Masquer la section 'Au sujet du gouvernement' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-about-gov-fr.html)
  * [Hide some links from the 'Corporate' section from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-corporate-en.html)
  * [Masquer certains liens de la section 'Organisation' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-corporate-fr.html)
  * [Hide 'About government' section and some links from the 'Corporate' section from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-support-en.html)
  * [Masquer la section 'Au sujet du gouvernement' et certains liens de la section 'Organisation' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-support-fr.html)
  * [Hide 'Support' section and some links from the 'Corporate' section from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-about-gov-en.html)
  * [Masquer la section 'Soutien' et certains liens de la section 'Organisation' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-about-gov-fr.html)
  * [Hide 'Support' and 'About government' sections from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-corporate-en.html)
  * [Masquer les sections 'Soutien' et 'Au sujet du gouvernement' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-corporate-fr.html)
  * [Hide 'Support' and 'About government' sections and some links from 'Corporate' section from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footers-en.html)
  * [Masquer les sections 'Soutien' et 'Au sujet du gouvernement' ainsi que certains liens de la section 'Organisation' du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footers-fr.html)

For the UAT testing, we are expecting that the following are reviewed and tested in the site footer section:
* [ ] All texts including: text link, visible heading, assistive technology (screen reader) only heading
* [ ] All links
* [ ] Visual rendering to match the user experience business requirement
* [ ] All the 3 item above (texts, links, visual) for each view port (extra-extra-small, extra-small, small, medium, large, extra-large)
* [ ] All the 4 item above (texts, links, visual, view port) for each possible configuration demoed of the site footer

\cc @delisma @GormFrank

**Comment by duboisp** [comment]
The above link for UAT testing has been updated with the latest change f593e23 made by @Garneauma

**Comment by duboisp** [comment]
The above link for UAT testing has been updated with the latest change e19b5752 made by @Garneauma

**Review by duboisp — APPROVED** [review]
I reviewed the change, and look good.

Note that the content of every working example pages contain content that has been updated.

I updated the UAT link to match the latest commit 53d3651

**Comment by duboisp** [comment]
I updated the UAT links to match the latest commit 5170929c

Some URL has changed for UAT, here all the URLs

- [Footer](https://universallabs.org/wet/labs/pr2043/sites/footers/footers-en.html)
- [Pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/footers-fr.html)
- [Hide contextual band from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-contextual-en.html)
- [Masquer la bande contextuelle du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-contextual-fr.html)
- [Hide main band from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-main-en.html)
- [Masquer la bande principale du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-main-fr.html)
- [Hide optional links from the sub-footer band](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-corporate-en.html)
- [Masquer les liens optionnels de la bande sous le pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footer-corporate-fr.html)
- [Hide the main band and optional links from the sub-footer band from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-contextual-en.html)
- [Masquer la bande principale et les liens optionnels de la bande sous le pied de page du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-contextual-fr.html)
- [Hide the contextual band and optional links from the sub-footer band from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-main-en.html)
- [Masquer la bande contextuelle et les liens optionnels de la bande sous le pied de page du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-main-fr.html)
- [Hide the contextual and main bands from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-corporate-en.html)
- [Masquer les bandes contextuelle et principale du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/only-footer-corporate-fr.html)
- [Hide the contextual and main footer bands as well as optional links from the sub-footer band from the footer](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footers-en.html)
- [Masquer les bandes contextuelle et principale ainsi que les liens optionnels de la bande sous le pied de page du pied de page](https://universallabs.org/wet/labs/pr2043/sites/footers/no-footers-fr.html)

\cc @delisma

**Review by duboisp — APPROVED** [review]
UAT Approved by DTO on November 25, 2021

> Re Sub-footer mobile views: the team here has agreed that the new mobile view shown below is good. 
> 
> *	no need for top-of-page element
> *	sub-footer links in single column w/ no bullet points

_(reference number WET-290 with PP on November 25, 2022 at 2:18 PM)_

Releasing a minor version for now to allow department to be prepared. We will do a major release of GCWeb when that new footer will be required to be applied on all web pages.

Note: I did local testing and code review for all previous changes that was made in this PR context.

**Pull request merged**
