### PR TITLE
Méli-mélo - 2021-5-conjunction

### PR DESCRIPTION
**Pull request by Christopher-O**
Added index page with all class types and multiple examples. Also included evergreen implementation plan and considerations.

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
Everything look good, but we would need you to add working example when the feature is used with the following CSS class:

* cnjnctn-col-90
* cnjnctn-col-80
* cnjnctn-col-75
* cnjnctn-col-70
* cnjnctn-col-60
* cnjnctn-col-40
* cnjnctn-col-30
* cnjnctn-col-25
* cnjnctn-col-20

**Comment by Christopher-O** [comment]
@duboisp  the additional examples and code snippets have been added.

**Review by duboisp — CHANGES_REQUESTED** [review]
We would need a small French working example page to illustrate at minimum the use of the CSS selector `html:lang(fr)`.

**Comment by Christopher-O** [comment]
@duboisp  should we keep the CSS selector at the html element (html:lang(fr)), or should we decouple it (*:lang(fr))?  I don't really see a need for someone to put an entire and/or statement in another language on a page...but then again it would make it more flexible.

**Review by duboisp — APPROVED** [review]

**Comment by duboisp** [comment]
I tested and reviewed this contribution to ensure all CSS is demoed and I confirm it don't conflict with wet-boew neither GCWeb.

**Review by duboisp — APPROVED** [review]

**Pull request merged**
