### PR TITLE
Updated Topic page - removed alert banner and changed H1 title

### PR DESCRIPTION
**Pull request by MaximMartel**
Updated as per Content and IA Spec 3.2

### CODE REVIEW

**Comment by MaximMartel** [comment]
@shawnthompson @lucas-hay

**Comment by MaximMartel** [comment]
https://maximmartel.github.io/GCWeb-UpdateTopic/topic-en.html

**Comment by MaximMartel** [comment]
@DK-TBS

**Comment by DK-TBS** [comment]
English topic page looks good too!

**Comment by MaximMartel** [comment]
Sweet :) check the french if you don't mind as well. Thanks @DK-TBS

**Comment by DK-TBS** [comment]
Roger that.  French is good too!

**Pull request merged**
