### PR TITLE
Documentation: Adding Design patterns component category

### PR DESCRIPTION
**Pull request by Garneauma**

### CODE REVIEW

**Comment by duboisp** [comment]
This seems to be content change, pre-approved after review and local testing

**Review by duboisp — CHANGES_REQUESTED** [review]
Tested locally and it do work as expected.

While we are waiting for the first design pattern, I recommend that we do create the container folder. You can do that by adding a `.gitkeep` file temporarily inside the folder which we can remove after there is one or a few design pattern.

Note: This PR is only a content change.

**Comment by Garneauma** [comment]
> While we are waiting for the first design pattern, I recommend that we do create the container folder. You can do that by adding a `.gitkeep` file temporarily inside the folder which we can remove after there is one or a few design pattern.

Thank you @duboisp, I was not aware that such file existed!

**Review by duboisp — APPROVED** [review]
Reviewed and tested locally, work as expected

This is a content change

**Pull request merged**
