### PR TITLE
Report a problem alignment with AEM pattern

### PR DESCRIPTION
**Pull request by delisma**

### CODE REVIEW

**Comment by duboisp** [comment]
Pre-approve after quick local testing to ensure it match what we have on Canada.ca.

This is a Major change

**Comment by StdGit** [comment]
this is a test

**Comment by GormFrank** [comment]
Needs to be documented.

**Comment by delisma** [comment]
> Needs to be documented.

Documented how? This pattern comes from the PP. The documentation that DTO have is for a pattern that includes `input=text` field

**Comment by duboisp** [comment]
https://github.com/wet-boew/GCWeb/blob/master/site/pages/gcweb-theme/release/dev-build.hbs

**Comment by duboisp** [comment]
@namjohn920 can you create a section in the dev-build that show the previous patter and the new pattern and what field need to be updated.

**Comment by GormFrank** [comment]
> @namjohn920 can you create a section in the dev-build that show the previous patter and the new pattern and what field need to be updated.

@namjohn920 any updates on this one?

**Comment by duboisp** [comment]
@GormFrank the build might fail, but I can't rebase david PR. There is no conflict and it build (dist) correctly on my work station. It is safe to merge.

**Comment by duboisp** [comment]
Also, I added the documentation in the release note 7.0

**Pull request merged**
