### PR TITLE
Try to fix build error by downgrading npm to what it was before?

### PR DESCRIPTION
**Pull request by andre-gh**

### CODE REVIEW

**Comment by andre-gh** [comment]
Test build, wait to see if it passes travis

**Comment by andre-gh** [comment]
Build passing, this is the fix

**Comment by nschonni** [comment]
Should just apply the same change as https://github.com/wet-boew/wet-boew/commit/bdffe629a93667eee1c43ecde791988d63a4aa0e

**Comment by andre-gh** [comment]
Ah, I assumed we were using npm@next for a recent reason rather than a legacy reason, I can PR that into all the branches.

**Comment by nschonni** [comment]
You might need to do this version of the fix on any of the themes that haven't been updated to `grunt-sass` 1.0.0, since that was the thing that was keeping them on Node 0.10 for the longest time.
You might not need to even pin the NPM version at all for the other repos though, since 0.10.40 might have a new enough NPM for those node-sass issues.

**Comment by andre-gh** [comment]
Ah yeah, some of those themes are still on old grunt-sass, I have pull requested a straight node version switchover, if they build fail I will fix them in the morning.

Thanks for your help

**Pull request merged**
