### PR TITLE
Build - Added Sub-resource basic integrity generation

### PR DESCRIPTION
**Pull request by duboisp**
The sub-resource integrity hash will be included with the release note.

### CODE REVIEW

**Comment by nschonni** [comment]
It looks like the lock file changes got missed here

**Comment by duboisp** [comment]
@nschonni Should I get it fixed before the GCWeb release or can I get it fixed after?

**Comment by nschonni** [comment]
I'm just looking now. It shouldn't affect the actual SRI, just possibly the build consistency if someone tries to go back and build. We only just added the lock to this repo, so it's not like they had that option before anyway :P

**Comment by duboisp** [comment]
ok great, I will finish the release then I will submit a PR with the updated lock file

**Pull request merged**
