### PR TITLE
Added section Focus on to homepage

### PR DESCRIPTION
**Pull request by MaximMartel**
As per IA Spec 3.2

### CODE REVIEW

**Comment by MaximMartel** [comment]
@shawnthompson

**Comment by MaximMartel** [comment]
https://maximmartel.github.io/GCWeb-focuson/home-en.html

**Comment by MaximMartel** [comment]
@DK-TBS

**Comment by DK-TBS** [comment]
Hi @MaximMartel!  The new "focus on" section looks right, but now that the 3 audience doormats have been added to the new row at the bottom, we should remove them from the other group above.  So the old audience doormats named "Seniors", "Aboriginals" and "Veterans" should be deleted.

**Comment by MaximMartel** [comment]
@DK-TBS Great! Thanks for this, I will remove the doormats mentioned above.

**Comment by MaximMartel** [comment]
Updated @DK-TBS

**Comment by DK-TBS** [comment]
@MaximMartel - I tried clearing my cache and doing a forced refresh of the page, but I'm still seeing the "Seniors", "Aboriginals" and "Veterans" items.  Those will have to be removed on the French side, as well.

**Comment by MaximMartel** [comment]
@DK-TBS i need to update my working example... ill do that right now :)

**Comment by MaximMartel** [comment]
@DK-TBS https://maximmartel.github.io//GCWeb-UpdateHomeEnFr/home-en.html | https://maximmartel.github.io//GCWeb-UpdateHomeEnFr/home-fr.html

**Comment by DK-TBS** [comment]
Looks good, but we should probably put the placeholder "Audience" labels in square brackets, to be consistent with the rest of the spec templates - "[Audience]".  We always try to mark placeholder text in square brackets like that to distinguish it from mandatory labels.  

Also, on the French side, the French version of the spec seems to have "Public cible" as the placeholder label, instead of just "Public".  So we should probably go with "[Public cible]".

**Comment by shawnthompson** [comment]
@DK-TBS Can you open up an issue for this change? This commit has been merged and closed.

Thanks!

**Comment by MaximMartel** [comment]
Ill do the changes that DK-TBS is asking once he submitted his issue :) Thanks @shawnthompson

**Pull request merged**
